sudo: required

services:
    - docker

language: bash

before_script:
    - "docker build -t idomyowntricks/autobuilds ."
    - "docker container run --detach --publish 8080:80 idomyowntricks/autobuilds"
    - docker ps

script:
    - while ! curl --retry 10 --retry-delay 5 -v http://0.0.0.0:8080 >/dev/null; do sleep 1; done
